### ISSUE TITLE
Никнеймы админов

### ISSUE THREAD

**Issue by CrazyHackGUT** [SB-MaterialAdmin/OldServer#15]
Перенесено [отсюда](https://github.com/SB-MaterialAdmin/Web/issues/100).

Оригинальный пост:
> Бесит что админы меняют свои никнеймы и когда нужно снять админку либо ещё что-то сделать то приходиться пользоваться поиском по steam Id.
Можно как то сделать чтобы в какое-то время сайт менял ники у админов.
**И ещё можно сделать как на faceit чтобы ник менялся у админа если не совпадал с бд**

**Comment by WhyFaust** [comment]
У меня просто сделан вывод на сервере, как админа в дб зовут
![image](https://user-images.githubusercontent.com/20227450/38456161-f34ed86e-3a89-11e8-9b61-78d3ffab10b7.png)

**Comment by megoRU** [comment]
@baferpro что за плагин? с репутацией)

**Comment by WhyFaust** [comment]
Admins list..

**Comment by CrazyHackGUT** [comment]
@baferpro проверь.

**Comment by WhyFaust** [comment]
Да, работает, ток сначала не понял.Либо плагин не скомпилировался, либо что-то ещё.Пришлось самому компилировать.
![image](https://user-images.githubusercontent.com/20227450/38456884-1e4212d6-3a92-11e8-8d8e-86bd1cf7e341.png)

**Comment by CrazyHackGUT** [comment]
Я не компилирую тестовые обновления)
