### ISSUE TITLE
Banned player still can connect in CSGO, L4D, L4D2

### ISSUE THREAD

**Issue by CrazyHackGUT** [SB-MaterialAdmin/OldServer#16]

**Comment by megoRU** [comment]
Баг есть)

**Comment by rsgua** [comment]
Та да у меня тоже есть баг. Как можно это отследить?

**Comment by CrazyHackGUT** [comment]
Если раньше считалось, что на старых версиях такого нет, то нынче эта фича вскрылась даже в оригинальном SB++. И чаще всего проявляется на CS:GO, L4D, L4D2 серверах.
В идеале, нужен дамп базы и SteamID игрока, который беспрепятственно заходит на сервер.

**Comment by rsgua** [comment]
я скинул тебе дамп банов и стим айди который смог обойти
Вот свежее:
http://bans.in-g.su/index.php?p=banlist&searchText=-EaglE-
http://bans.in-g.su/index.php?p=banlist&searchText=%D0%90%D0%BD%D0%B3%D0%B5%D0%BB%D0%B8%D0%BD%D0%B0
http://in-g.su/sb_bans.sql

вот взял с дампа
вот чувака банят первый раз:
(68109, '95.53.205.29', 'STEAM_1:1:96138667', '-EaglE-', 1513081481, 1513081481, 0, 'Валхак', 1138, '178.150.156.226', 8, 'RU', NULL, NULL, NULL, -1, NULL),
вот второй раз банят
(68111, '95.53.205.29', 'STEAM_1:1:96138667', '-EaglE-', 1513082356, 1513082356, 0, 'Обход бана', 1138, '178.150.156.226', 8, 'RU', NULL, NULL, NULL, -1, NULL),
не вижу разницы
вот третий раз и четвертый раз банят
(68114, '95.53.205.29', 'STEAM_1:1:96138667', '-EaglE-', 1513083058, 1513083058, 0, 'Обход бана', 1138, '178.150.156.226', 8, 'RU', NULL, NULL, NULL, -1, NULL),
(68115, '95.53.205.29', 'STEAM_1:1:96138667', '-EaglE-', 1513083095, 1513083095, 0, 'Обход бана', 1138, '178.150.156.226', 8, 'RU', NULL, NULL, NULL, -1, NULL),

**Comment by CrazyHackGUT** [comment]
Проблема всё ещё актуальна даже после обновления на последний коммит?

**Comment by megoRU** [comment]
@rsgua 
![image](https://user-images.githubusercontent.com/23276305/33890712-136b97f2-df65-11e7-9de7-38323bc955ef.png)

**Comment by CrazyHackGUT** [comment]
@megowot я в плагине применил фикс, за счёт чего эта операция по идее не нужна.

**Comment by megoRU** [comment]
@CrazyHackGUT а может нужна все же?

**Comment by CrazyHackGUT** [comment]
@megowot По идее нет. Хотя не проверял этот момент.

**Comment by megoRU** [comment]
@rsgua 
@CrazyHackGUT 
Нужно делать, так как база данных повреждена (ну вы поняли)
Он же ее чинит.

**Comment by CrazyHackGUT** [comment]
@megowot Она не совсем повреждена. Хотя это можно и так назвать.
Я всё ещё не понимаю, если честно, почему эта ошибка возникает.
К слову, пока не обновляйтесь. Создал ещё одну ошибку своим "кривым апдейтом"...

**Comment by CrazyHackGUT** [comment]
Вот теперь всё должно быть хорошо.
Протестируйте и отпишитесь.

**Comment by rsgua** [comment]
Вроде все ок

**Comment by CrazyHackGUT** [comment]
Проблема внезапно снова проявляется. По крайней мере, у меня точно.
У кого-нибудь она ещё есть?
![image](https://i.imgur.com/lVG9BD9.png)

**Comment by rsgua** [comment]
запрос напиши я посмтрю у себя

**Comment by CrazyHackGUT** [comment]
```sql
SELECT 
    COUNT(*)
FROM 
    `sb_bans` 
WHERE 
    `type` = -1 
```

**Comment by rsgua** [comment]
да 338 банов

SELECT 
    COUNT(*)
FROM 
    `sb_bans` 
WHERE 
    `type` = -1 

нужен фикс плагина

**Comment by rsgua** [comment]
дай запрос на замену

**Comment by CrazyHackGUT** [comment]
Не пойму, почему оно в итоге снова не исправлено, если в первые дни вроде как все ок было. 
28-го посмотрю еще раз более плотно на проблему. Теория есть, что такое происходит только при бане через команду, и если выдавать через меню, то все ок.

**Comment by CrazyHackGUT** [comment]
Гит решил закрыть обсуждение с новым коммитом, но я пока с ним не согласен.
Тестируем.

**Comment by megoRU** [comment]
@CrazyHackGUT так вроде все хорошо можно закрывать

**Comment by CrazyHackGUT** [comment]
**НАКОНЕЦ-ТО!**
