### ISSUE TITLE
ADMINSEEALL

### ISSUE THREAD

**Issue by megoRU** [SB-MaterialAdmin/OldServer#26]
![image](https://user-images.githubusercontent.com/23276305/44632973-ec504800-a98c-11e8-9336-0fa482f581f6.png)
когда флаг у админа Z это функция пропадает. хз в чем дело я не шарю.

**Comment by CrazyHackGUT** [comment]
Нужно больше информации.
Что за плагин на скриншоте?

**Comment by megoRU** [comment]
кхм гейарена + просто обнова союрсмода....

**Comment by megoRU** [comment]
я хз что за плагин ибо в ФТП его не видно (они боятся что мы их украдем)

**Comment by megoRU** [comment]
https://hlmod.ru/threads/admin-see-all.19697/
хотя вот тут что то есть

**Comment by BlackYuzia** [comment]
ГейАрена... А это чет новенькое :D

**Comment by megoRU** [comment]
ахах ну майарена) как еще назвать то...
