### ISSUE TITLE
Database error: Duplicate entry

### ISSUE THREAD

**Issue by megoRU** [SB-MaterialAdmin/OldServer#29]
L 01/08/2019 - 22:50:11: [sbpp_main.smx] Database error: Duplicate entry ' mego' for key 'user'

Как исправить?

**Comment by megoRU** [comment]
уже понял

**Comment by megoRU** [comment]
кстати @CrazyHackGUT когда устанавливаешь веб часть ты вписываешь свой STEAM ID но прикол в том что хоть ты тресни но админку на сервер ты не получишь даже если себе выдашь группу со всеми правами... Сложно обьяснить но я обычно создаю сайт на другого steam id

**Comment by CrazyHackGUT** [comment]
Я понял, кажется.
Это не баг.

После добавления сервера, забываете вручную в редактировании админа поставить галочку на сервере. Потому СБ его и не загружает. Доступа-то к серверу у админа явного нет.

**Comment by megoRU** [comment]
Я добавлял галочку) Нет доступа. Если так нужно могу протестить... Сейчас займусь

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/50898985-d2863d80-1421-11e9-8e19-4e3a49a63c20.png)
окей ты выиграл.
