### ISSUE TITLE
CVAR для управления включения/отключения выбора типа бана

### ISSUE THREAD

**Issue by kilroy98** [SB-MaterialAdmin/OldServer#3]
Думаю логично, что стоит добавить квар, дабы можно было эту функцию отключать. 
Вот у меня, например, стоит изменённый SourceSleuth, который, при попытке обойти бан, сам банит по IP и функция выбора типа бана в админке, лично мне по сути не нужна.

Это не горит, как будет свободная минута, тогда и сделается. 
P.S. Хотя может через некоторое время я изменю своё мнение на счёт этого, но квар всё же не помешает :D

**Comment by CrazyHackGUT** [comment]
Чекай.

**Comment by kilroy98** [comment]
При 0 воркает, при 1 не смотрел, ибо лень xD
