### ISSUE TITLE
(Возможно) Баг с выводом на первое место игрока, за которым наблюдаешь

### ISSUE THREAD

**Issue by kilroy98** [SB-MaterialAdmin/OldServer#4]
Лично у меня игрок, за которым наблюдаешь, выводится, только тогда, когда камера отдалена или свободно летает, если смотреть от лица игрока - его не выводит. CSSv34 SM 1.7.3
И ещё, в админке теперь почему-то не показывается айди игрока после его ника в круглых скобках, раньше было.

**Comment by CrazyHackGUT** [comment]
В CSS v34 видимо немного отличаются константы spec mode. Надо будет глянуть.
Если есть возможность, скинь в ЛС в [Telegram](https://t.me/Kruzya) клиент CSS v34 и IP сервера. И админку для тестов, да :D

**Comment by CrazyHackGUT** [comment]
**Итог тестирований**: На CSS v34 (а конкретно в Source SDK 2006) немного отличаются константы при наблюдении за игроком. А именно:
- **Free camera**: SDK 2006 - 5, другие движки 3
- **1st person**: SDK 2006 - 3, другие движки 5
- **3st person**: SDK 2006 - 4, другие движки 4

**Comment by CrazyHackGUT** [comment]
Теперь всё должно быть чики-пуки. Однако призываю всех администраторов протестировать данный фикс в других играх.
Я не исключаю косяка со своей стороны при исправлении данной фичи движка SDK 2006.

**Comment by CrazyHackGUT** [comment]
Проблема более не поднималась. Закрываю.
