### ISSUE TITLE
Информативный бан

### ISSUE THREAD

**Issue by megoRU** [SB-MaterialAdmin/OldServer#5]
Когда банишь игрока есть. Когда игрок заходит ему только пишет "Вам был запрещен доступ к этому серверу"

**Comment by CrazyHackGUT** [comment]
Игрок получил бан на уровне движка.
SourceBans не может влиять на причину "кика" таких банов.

**Comment by megoRU** [comment]
@CrazyHackGUT в прошлых версиях когда игрок с активным баном заходил на сервер ему писало кто забанил насколько и так далее

**Comment by CrazyHackGUT** [comment]
@megowot в этой так же.
Но надо различать "бан от СБ" и "бан от движка".

В первом случае, как раз таки пишется, кто забанил, время, и причину.
Во втором нет.

**P.S.**: После первой попытки захода, СБ выдаёт бан в движке на 5 минут для защиты БД от флуда коннектами.
