### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by rsgua** [SB-MaterialAdmin/OldServer#8]
И так у меня почему-то сб багается и при выборе бана опеределнного игрока тупо меню закрывается.
И еще бывает такое что забаненные игроки заходят на сервер хоть они в бане!

**Comment by CrazyHackGUT** [comment]
https://github.com/SB-MaterialAdmin/OldServer/blob/master/addons/sourcemod/scripting/sbpp_main.sp#L50 
Декомментируешь, компилируешь. Когда сб снова кого-то забаненного пропустит, скидываешь сюда файл `/addons/sourcemod/logs/sourcebans.log`

**Comment by rsgua** [comment]
Такс этот баг когда через админ меню не баниться появляется в одно время когда забаненные могут заходить на сервер
И логи чистые! Я перекомпилил тут что ты скинул!
Я думаю это присходит от разрывов с бд и я так понимаю в сорес бане нет реконекта. Но я могу и ошибатся!

**Comment by CrazyHackGUT** [comment]
Переконнект есть.
Не совсем понял пост выше. Запятые можете расставить?

**Comment by rsgua** [comment]
Не работает реконет вот я офнул базу и все этот баг

**Comment by CrazyHackGUT** [comment]
Ну а как он должен подключиться к отключенной базе?
Вы конкретнее описывайте производимые действия.

**Comment by rsgua** [comment]
ну типа проверять если есть подключения то подключать, а то сейчас если пропало соедение и потом появилось то оно не подключится

**Comment by CrazyHackGUT** [comment]
SourceMod DBI сам не знает толком-то, когда соединение есть, а когда его нет. А тут Вы предлагаете как-то проверять его наличие.

**Comment by rsgua** [comment]
ну старая версию работала нормально

**Comment by CrazyHackGUT** [comment]
Между старой и новой версией изменений в соединении к БД не было.
Вы точно пересобирали sourcebans с декомментированым `#define DEBUG`?

**Comment by rsgua** [comment]
да

**Comment by rsgua** [comment]
и так поставил новою версию и та же беда и включил при этом FloodControl 1
но та же проблема что была и раньше только меню уже закрывается не при выборе игрока а при выборе STEAM ID или IP

**Comment by CrazyHackGUT** [comment]
Эта переменная не на соединение с базой влияет :)
Читать комментарии в конфиге надо.

**Comment by rsgua** [comment]
и еще включил "EnableSelectingBanType"    "1"

**Comment by rsgua** [comment]
а что делать тогда с плагином?

**Comment by CrazyHackGUT** [comment]
Вы мне не можете уже хрен знает сколько скинуть debug-лог, который я Вас прошу аж с самого начала создания обсуждения!
![screenshot](https://i.imgur.com/IyOEiiG.png)
Я не могу ничего сделать, пока его не увижу, ибо не могу достоверно определить причину проблемы.
С реконнектом к базе тоже самое. Я не могу решить проблему, которая ни разу не была показана хотя бы в виде записи в логах SourceMod.

**Comment by rsgua** [comment]
логи http://in-g.su/sourcebans.log

**Comment by CrazyHackGUT** [comment]
Проблема с закрывающейся меню после выбора игрока решена. Про коннекты надо посмотреть.

**Comment by rsgua** [comment]
проблема решена
